type Query {
	getCurrentUser: User

	getPosts: [Post]
	getMyPosts(user_id: String!): [Post]
}

type Mutation {
	signupUser(username: String!, email: String, password: String!): Token
	signinUser(username: String!, password: String!): Token

	createPost(caption: String!, imageUrl: String!, createdBy: ID!): Post
}

type Token {
	token: String!
}

type User {
	_id: ID
	username: String!
	email: String!
	password: String
	createdDate: String
	avatar: String!
	likedImage: [Post]
}

type Post {
	_id: ID
	caption: String!
	imageUrl: String!
	createdDate: String!
	createdBy: User!
	likes: [String]
	comments: [Comment]
}

type Comment {
	createdBy: User!
	commentBody: String!
	commentDate: String!
}
